clear;
clf;
clc;
I=imread('enc_monkey2.bmp');

  Red = I(:,:,1);
  Green = I(:,:,2);
  Blue = I(:,:,3);
       entropy_red = entropy(Red);
       entropy_green = entropy(Green);
       entropy_blue = entropy(Blue);
       J_red = medfilt2(Red);
       R_red = corr2(Red,J_red);
       J_green = medfilt2(Green);
       R_green = corr2(Green,J_green);
       J_blue = medfilt2(Blue);
       R_blue = corr2(Blue,J_blue);
       fprintf("Correlation Coefficient for red channel: %3.4f\n",R_red);
       fprintf("Correlation Coefficient for green channel: %3.4f\n",R_green);
       fprintf("Correlation Coefficient for blue channel: %3.4f\n",R_blue);
       fprintf("Entropy of red channel: %3.4f\n", entropy_red);
       fprintf("Entropy of green channel: %3.4f\n", entropy_green);
       fprintf("Entropy of blue channel: %3.4f\n", entropy_blue);
       [yRed, x] = imhist(Red);
       [yGreen, x] = imhist(Green);
       [yBlue, x] = imhist(Blue);
       
       tcl = tiledlayout(1,2);
       nexttile;
       plot(x, yRed, 'Red', x, yGreen, 'Green', x, yBlue, 'Blue');
       legend('Red','Green','Blue');
       xlabel("Value");
       ylabel("# Occurrences");
       nexttile;
       bar(yRed, 'Red') ,hold on , bar(yGreen, 'Green'), hold on ,bar( yBlue, 'Blue');
       legend('Red','Green','Blue');  
       xlabel("Value");
       ylabel("# Occurrences");
       title(tcl,"Encrypted Image Histogram");